In [132]:
import json
import pandas as pd

In [133]:
value_df = pd.read_csv("2025-10-13 (1).csv")
momentum_df = pd.read_csv('u1_stock_list.csv')

In [134]:
with open('names.json','r') as file:
    tickers = json.load(file)

In [135]:
print(tickers)

['ADANIPOWER', 'AJANTPHARM', 'AKZOINDIA', 'APARINDS', 'ASTRAMICRO', 'AVANTIFEED', 'BAJAJ-AUTO', 'BANCOINDIA', 'BEML', 'CEATLTD', 'CEMPRO', 'CHAMBLFERT', 'CHOLAFIN', 'COROMANDEL', 'CREDITACC', 'DEEPAKFERT', 'DLF', 'ECLERX', 'ELECTCAST', 'FIEMIND', 'GABRIEL', 'GMDCLTD', 'GODFRYPHLP', 'GOKEX', 'GPIL', 'GRANULES', 'GRSE', 'GULFOILLUB', 'HAL', 'HBLENGINE', 'HINDZINC', 'IMFA', 'INDIGO', 'JINDALSTEL', 'JPPOWER', 'KIRLOSBROS', 'KSCL', 'M&M', 'MAHKTECH', 'MANAPPURAM', 'MOM100', 'MRF', 'MUTHOOTFIN', 'NATIONALUM', 'NIFTYBEES', 'NTPC', 'PCBL', 'PGEL', 'POWERMECH', 'PRICOLLTD', 'REDINGTON', 'REFEX', 'RVNL', 'SARDAEN', 'SGBJUN31I', 'SUZLON', 'SWANCORP', 'TATAPOWER', 'TECHM', 'TI', 'TIINDIA', 'TIMETECHNO', 'TRENT', 'VEDL', 'WABAG', 'WELCORP']

In [136]:
value_df['ROE_ROCE_greater_than_15'].unique()

array([ True])

In [137]:
momentum_df.columns

Index(['Unnamed: 0', 'Stock', 'Index Satisfied', 'Year_1_ShM', 'Year_1_Beta',
       'Year_1_Index_Satisfied', 'Year_2_ShM', 'Year_2_Beta',
       'Year_2_Index_Satisfied', 'Year_3_ShM', 'Year_3_Beta',
       'Year_3_Index_Satisfied', 'Year_4_ShM', 'Year_4_Beta',
       'Year_4_Index_Satisfied', 'Year_5_ShM', 'Year_5_Beta',
       'Year_5_Index_Satisfied', 'Min(ShM)', 'Max(ShM)', 'Avg(ShM)'],
      dtype='object')

In [138]:
final_df = pd.DataFrame()

In [139]:
tickers = [ticker+'.NS' for ticker in tickers]

In [140]:
print(tickers)

['ADANIPOWER.NS', 'AJANTPHARM.NS', 'AKZOINDIA.NS', 'APARINDS.NS', 'ASTRAMICRO.NS', 'AVANTIFEED.NS', 'BAJAJ-AUTO.NS', 'BANCOINDIA.NS', 'BEML.NS', 'CEATLTD.NS', 'CEMPRO.NS', 'CHAMBLFERT.NS', 'CHOLAFIN.NS', 'COROMANDEL.NS', 'CREDITACC.NS', 'DEEPAKFERT.NS', 'DLF.NS', 'ECLERX.NS', 'ELECTCAST.NS', 'FIEMIND.NS', 'GABRIEL.NS', 'GMDCLTD.NS', 'GODFRYPHLP.NS', 'GOKEX.NS', 'GPIL.NS', 'GRANULES.NS', 'GRSE.NS', 'GULFOILLUB.NS', 'HAL.NS', 'HBLENGINE.NS', 'HINDZINC.NS', 'IMFA.NS', 'INDIGO.NS', 'JINDALSTEL.NS', 'JPPOWER.NS', 'KIRLOSBROS.NS', 'KSCL.NS', 'M&M.NS', 'MAHKTECH.NS', 'MANAPPURAM.NS', 'MOM100.NS', 'MRF.NS', 'MUTHOOTFIN.NS', 'NATIONALUM.NS', 'NIFTYBEES.NS', 'NTPC.NS', 'PCBL.NS', 'PGEL.NS', 'POWERMECH.NS', 'PRICOLLTD.NS', 'REDINGTON.NS', 'REFEX.NS', 'RVNL.NS', 'SARDAEN.NS', 'SGBJUN31I.NS', 'SUZLON.NS', 'SWANCORP.NS', 'TATAPOWER.NS', 'TECHM.NS', 'TI.NS', 'TIINDIA.NS', 'TIMETECHNO.NS', 'TRENT.NS', 'VEDL.NS', 'WABAG.NS', 'WELCORP.NS']

In [141]:
final_df['Portfolio Ticker'] =  tickers

In [142]:
final_df

   Portfolio Ticker
0     ADANIPOWER.NS
1     AJANTPHARM.NS
2      AKZOINDIA.NS
3       APARINDS.NS
4     ASTRAMICRO.NS
..              ...
61    TIMETECHNO.NS
62         TRENT.NS
63          VEDL.NS
64         WABAG.NS
65       WELCORP.NS

[66 rows x 1 columns]

In [143]:
# Assuming 'final_df' is the DataFrame where you want to add the column.
final_df['Value Satisfied'] = False # Initialize the column

# Set 'Ticker' as the index of value_df for fast lookups (optional but better)
value_df_indexed = value_df.set_index('Ticker')

for index, ticker in final_df['Portfolio Ticker'].items():
    # 1. Check if the ticker exists in the value_df index
    if ticker in value_df_indexed.index:
        # 2. Use .loc[] to safely look up the 'ROE_ROCE_greater_than_15' status
        status = value_df_indexed.loc[ticker, 'ROE_ROCE_greater_than_15']

        # NOTE: .loc[ticker] could return a Series (multiple rows) if Tickers aren't unique.
        # This code assumes a single unique Ticker match.
        if (status == True):
            final_df.loc[index, 'Value Satisfied'] = True

In [144]:
final_df

   Portfolio Ticker  Value Satisfied
0     ADANIPOWER.NS            False
1     AJANTPHARM.NS             True
2      AKZOINDIA.NS             True
3       APARINDS.NS             True
4     ASTRAMICRO.NS            False
..              ...              ...
61    TIMETECHNO.NS            False
62         TRENT.NS            False
63          VEDL.NS            False
64         WABAG.NS            False
65       WELCORP.NS             True

[66 rows x 2 columns]

In [145]:
final_df['Value Satisfied'].value_counts()

Value Satisfied
False    43
True     23
Name: count, dtype: int64

In [146]:
# Assuming 'final_df' is the DataFrame where you want to add the column.
final_df['Momentum Satisfied'] = False # Initialize the column

# Set 'Ticker' as the index of value_df for fast lookups (optional but better)
value_df_indexed = momentum_df.set_index('Stock')

for index, ticker in final_df['Portfolio Ticker'].items():
    # 1. Check if the ticker exists in the value_df index
    if ticker in value_df_indexed.index:
        final_df.loc[index, 'Momentum Satisfied'] = True

In [147]:
final_df

   Portfolio Ticker  Value Satisfied  Momentum Satisfied
0     ADANIPOWER.NS            False               False
1     AJANTPHARM.NS             True               False
2      AKZOINDIA.NS             True               False
3       APARINDS.NS             True               False
4     ASTRAMICRO.NS            False                True
..              ...              ...                 ...
61    TIMETECHNO.NS            False               False
62         TRENT.NS            False               False
63          VEDL.NS            False               False
64         WABAG.NS            False               False
65       WELCORP.NS             True                True

[66 rows x 3 columns]

In [148]:
final_df['Momentum Satisfied'].value_counts()

Momentum Satisfied
False    56
True     10
Name: count, dtype: int64

In [149]:
final_df['Value Momentum Satisfied'] = final_df['Value Satisfied'] | final_df['Momentum Satisfied']
final_df

,Portfolio Ticker,Value Satisfied,Momentum Satisfied,Value Momentum Satisfied
0,ADANIPOWER.NS,False,False,False
1,AJANTPHARM.NS,True,False,True
2,AKZOINDIA.NS,True,False,True
3,APARINDS.NS,True,False,True
4,ASTRAMICRO.NS,False,True,True
...,...,...,...,...
61,TIMETECHNO.NS,False,False,False
62,TRENT.NS,False,False,False
63,VEDL.NS,False,False,False
64,WABAG.NS,False,False,False
65,WELCORP.NS,True,True,True

In [150]:
final_df['Value Momentum Satisfied'].value_counts()

Value Momentum Satisfied
False    38
True     28
Name: count, dtype: int64

In [131]:
final_df.to_excel('PortFolio F1 Satisfied Stocks.xlsx',index=False)